app = "locuspocusbot"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ams"
processes = []

[env]
  Logging__LogLevel__Default = "Information"
  Logging__LogLevel__Microsoft = "Warning"
  "Logging__LogLevel__System.Net.Http.HttpClient" = "Warning"
