name: Build and push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Build Docker image
      run: |
        docker build -t bot .
        docker tag bot matteocontrini/locuspocusbot:latest
        docker tag bot matteocontrini/locuspocusbot:$(git rev-parse --short HEAD)
        docker images
    
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    
    - name: Push to Docker Hub
      run: docker push matteocontrini/locuspocusbot
